### PR TITLE
72 fix: user doesn't redirected to home/dashboard after successfully logged in

### LINKED ISSUE #72: bug: user doesn't redirected to home/dashboard after successfully logged in.
## How to reproduce:
- In `/login` page, after user has successfully logged in, user stays in the page rather than redirected to home/dashboard.

## Expected behaviour:
- User to be redirected to either home/dashboard after successfully logged in

### PR DESCRIPTION
**Pull request by ttnsy**
- Remove `setTimeout` in `handleSubmitLogin`
- push to `/` after logged in
- add `router.refresh()` after `router.push()`

### CODE REVIEW

File: src/app/login/components/LoginForm.jsx [hunk 1]
```diff
@@ -13,15 +13,12 @@ export const LoginForm = () => {
   const [password, setPassword] = useState("");
 
   const handleSubmitLogin = async (e) => {
-    setLoading(true);
     e.preventDefault();
     try {
       await login(email, password);
       toast.success("Logged in successfully");
-      setTimeout(() => {
-        router.push("/dashboard");
```
Comment (alfonsusac) [inline src/app/login/components/LoginForm.jsx:22]: We still need user to get redirected to /dashboard after logging in

**Review by alfonsusac — CHANGES_REQUESTED** [review]

File: src/app/login/components/LoginForm.jsx (hunk 1 above)
Comment (ttnsy) [reply src/app/login/components/LoginForm.jsx:22]: resolved in [506de6f](https://github.com/alfonsusac/devscale-eventmaker/pull/93/commits/506de6f492726c69337dacccc0e4abe709052ab2)

**Review by alfonsusac — APPROVED** [review]
lgtm
