### PR TITLE
fix: add proper image

### LINKED ISSUE #75: Bug: Pull the correct Image Event
Most of events have the correct image now. Lets pull it

### PR DESCRIPTION
**Pull request by rizaardiyanto1412**
Issue: https://github.com/alfonsusac/devscale-eventmaker/issues/75

### CODE REVIEW

File: src/components/EventItem.jsx [hunk 1]
```diff
@@ -1,17 +1,27 @@
...
+import Image from "next/image";
 
 export const EventItem = async ({ events }) => {
-  console.log(events.image);
   return (
     <div className="card card-compact bg-base-100 shadow-lg">
-      <div className="h-32 bg-cover bg-center rounded-t-xl"></div>
+      <div className="h-40 max-h-[500px] bg-cover bg-center rounded-t-xl">
+        <Image
+          src={events.image}
```
Comment (alfonsusac) [inline src/components/EventItem.jsx:11]: does adding the "unoptimized" props in <Image/> without adding the remotepattern in nextjs.config works?

**Review by alfonsusac — CHANGES_REQUESTED** [review]

**Review by alfonsusac — APPROVED** [review]
